### PR TITLE
feat: add delimiter BlobListOption

### PR DESCRIPTION
**Pull request by athakor**

### CODE REVIEW

**Review by rahulKQL — APPROVED** [review]

**Comment by rahulKQL** [comment]
any test case?

**Comment by athakor** [comment]
> any test case?

@rahulKQL thanks for reviewing but i dont thinks so we need any testcase for this method.

**Comment by dmitry-fa** [comment]
@athakor I think some tests are required. Otherwise, this change will bring uncovered code.
The similar method `public static BlobListOption currentDirectory()` is covered by IT test.
To run a new case of storage ITStorageTest you need to comment  `iamStub.setIamPolicy(setIamPolicyRequest);`

**Comment by athakor** [comment]
> @athakor I think some tests are required. Otherwise, this change will bring uncovered code.
> The similar method `public static BlobListOption currentDirectory()` is covered by IT test.
> To run a new case of storage ITStorageTest you need to comment `iamStub.setIamPolicy(setIamPolicyRequest);`

@dmitry-fa done

**Review by pmakani — APPROVED** [review]

**Pull request closed without merging**
